project_id = "wroqliryvssdljfmyjtu"

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.generate-download-link]
verify_jwt = false

[functions.verify-bank-details]
verify_jwt = false

[functions.get-paystack-banks]
verify_jwt = false